- name: Disallow root login remotely
  command: >
    mysql -u root -p"{{mariadb_root_password}}" -NBe "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
  changed_when: False
  when: "'root' not in mariadb_accept_outbound_login_for_these_users"

- name: Add followings databases to mariadb
  mysql_db:
    login_user: root
    login_password: "{{ mariadb_root_password|mandatory }}"
    name: "{{ item }}"
    state: present
  loop: "{{ mariadb_databases | default([]) }}"
  when: mariadb_databases is defined and mariadb_databases | length > 0

- name: Add followings users to mariadb
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password|mandatory }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host | default('localhost') }}"
    priv: "{{ item.priv | default('*.*:ALL,GRANT') }}"
  loop: "{{ mariadb_users | default([]) }}"
  when: mariadb_users is defined and mariadb_users | length > 0
